modLoader = "javafml"
loaderVersion = "[47,)"
license = "CC-2.0"
issueTrackerURL="${mod_url}"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="${mod_url}"
logoFile = "assets/icon.png"
credits = "retroPacifist, computerCorvidae, Chaottic, MsRandom, YaBoiChips, Cibernet83, Dweblenod"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[${forge_version},)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
mandatory=true
versionRange="[4.2,)"
ordering="NONE"
side="BOTH"

